In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from datetime import datetime


In [ ]:
df=pd.read_csv("data.csv")

In [ ]:
df.head()

number_people                       date  timestamp  day_of_week  \
0             37  2015-08-14 17:00:11-07:00      61211            4   
1             45  2015-08-14 17:20:14-07:00      62414            4   
2             40  2015-08-14 17:30:15-07:00      63015            4   
3             44  2015-08-14 17:40:16-07:00      63616            4   
4             45  2015-08-14 17:50:17-07:00      64217            4   

   is_weekend  is_holiday  temperature  is_start_of_semester  \
0           0           0        71.76                     0   
1           0           0        71.76                     0   
2           0           0        71.76                     0   
3           0           0        71.76                     0   
4           0           0        71.76                     0   

   is_during_semester  month  hour  
0                   0      8    17  
1                   0      8    17  
2                   0      8    17  
3                   0      8    17  
4                   0      8    17

In [ ]:
df["date"]=pd.to_datetime(df["date"],utc=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62184 entries, 0 to 62183
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype              
---  ------                --------------  -----              
 0   number_people         62184 non-null  int64              
 1   date                  62184 non-null  datetime64[ns, UTC]
 2   timestamp             62184 non-null  int64              
 3   day_of_week           62184 non-null  int64              
 4   is_weekend            62184 non-null  int64              
 5   is_holiday            62184 non-null  int64              
 6   temperature           62184 non-null  float64            
 7   is_start_of_semester  62184 non-null  int64              
 8   is_during_semester    62184 non-null  int64              
 9   month                 62184 non-null  int64              
 10  hour                  62184 non-null  int64              
dtypes: datetime64[ns, UTC](1), float64(1), int64(9)
memory usage: 5.2 M

In [ ]:
df["minute"]=df["date"].dt.minute
df["minute"]

0         0
1        20
2        30
3        40
4        50
         ..
62179    42
62180    52
62181     2
62182    12
62183    22
Name: minute, Length: 62184, dtype: int64

In [ ]:
df["second"]=df["date"].dt.second

In [ ]:
df["dates"]=df["date"].dt.date
df["dates"] = pd.to_datetime(df["dates"]).dt.strftime("%Y%m%d")
df["dates"][:10]
df["dates"] = pd.to_numeric(df["dates"])


In [ ]:
gym=df.drop("date",axis=1)

In [ ]:
gym["dates"].dtypes

dtype('int64')

In [ ]:
gym["dates"][:10]

0    20150815
1    20150815
2    20150815
3    20150815
4    20150815
5    20150815
6    20150815
7    20150815
8    20150815
9    20150815
Name: dates, dtype: int64

In [ ]:
gym.isna().sum()

number_people           0
timestamp               0
day_of_week             0
is_weekend              0
is_holiday              0
temperature             0
is_start_of_semester    0
is_during_semester      0
month                   0
hour                    0
minute                  0
second                  0
dates                   0
dtype: int64

## Training model with Ridge

In [ ]:
# import algorihtm/estimator
from sklearn.linear_model import Ridge
#setup random seeds
np.random.seed(42)

#create data
x=gym.drop(["number_people"],axis=1)
y=gym["number_people"]

# split data into train and test sets
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

#instantiate and fit the model (on the training set)
model =Ridge()
model.fit(x_train,y_train)

# check the score of model (on the test set)
model.score(x_test,y_test)

0.606246771222107

## _Training a model with RandomForestRegressor_

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
np.random.seed(42)
#fit the data
X=gym.drop(["number_people"],axis=1)
y=gym["number_people"]

#split the data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

model=RandomForestRegressor()

model.fit(X_train,y_train)


RandomForestRegressor()

In [ ]:
model.score(X_test,y_test)

0.9426610920644627

## _lets predict the model_

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
np.random.seed(42)
#fit the data
X=gym.drop(["number_people"],axis=1)
y=gym["number_people"]

#split the data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

model=RandomForestRegressor()

model.fit(X_train,y_train)
y_preds=model.predict(X_test)
a=y_preds # converting exponent no.
map('{:.2f}%'.format,a)


In [ ]:
a[:10]

array([ 0.81, 33.6 , 25.65, 65.58,  0.42, 81.13, 15.37, 48.68, 28.12,
       58.61])

#### Here finding Mean Absolute Error

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)

3.7146675243225857

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(model,X,y)
np.random.seed(42)
cross_val_score(model,X,y,cv=5,scoring=None)

array([-0.25570307,  0.46690568,  0.6593598 ,  0.70465118,  0.4179958 ])

In [ ]:
np.random.seed(42)

# single training and test split score
model_single_score=model.score(X_test,y_test)

# take the mean of cross_val_score
model_cross_val_score=np.mean(cross_val_score(model,X,y))

#compare the two
model_single_score,model_cross_val_score

(0.9426610920644627, 0.39864187767266246)

In [ ]:
y_test.mean()

29.04221275227145

### ___Regression Model Evaluation___

In [ ]:
from sklearn.metrics import r2_score

# fill an array with y_test mean just for demonstration
y_test_mean=np.full(len(y_test),y_test.mean())

In [ ]:
y_test_mean[:10]

array([29.04221275, 29.04221275, 29.04221275, 29.04221275, 29.04221275,
       29.04221275, 29.04221275, 29.04221275, 29.04221275, 29.04221275])

In [ ]:
r2_score(y_true=y_test,
         y_pred= a)

0.9426610920644627

##### Mean absolute error

In [ ]:
from sklearn.metrics import mean_absolute_error
np.random.seed(42)
y_preds=model.predict(X_test)
mae=mean_absolute_error(y_test,y_preds)
mae

10.656102257545719

In [ ]:
a[:10]

array([ 0.81, 33.6 , 25.65, 65.58,  0.42, 81.13, 15.37, 48.68, 28.12,
       58.61])

In [ ]:
y_test[:10]

44802     1
51279    27
36816    26
2503     71
53035     0
2399     79
54313    18
24735    58
47458    34
18250    64
Name: number_people, dtype: int64

In [ ]:
df=pd.DataFrame(data={'actual value':y_test,
                      'predicted value':a})
df['Difference']=df['predicted value']-df["actual value"]
df.head(10)

actual value  predicted value  Difference
44802             1             0.81       -0.19
51279            27            33.60        6.60
36816            26            25.65       -0.35
2503             71            65.58       -5.42
53035             0             0.42        0.42
2399             79            81.13        2.13
54313            18            15.37       -2.63
24735            58            48.68       -9.32
47458            34            28.12       -5.88
18250            64            58.61       -5.39

In [ ]:
df['Difference'].mean() # here negative value is also included thats why it is different

0.08372758703867468

In [ ]:
np.abs(df['Difference']).mean()

3.7146675243225933

#### Mean squared error

In [ ]:
from sklearn.metrics import mean_squared_error

mse=mean_squared_error(y_test,y_preds)
mse

203.51045045263305

In [ ]:
df["Squared_Difference"]=np.square(df["Difference"])
df.head()

actual value  predicted value  Difference  Squared_Difference
44802             1             0.81       -0.19              0.0361
51279            27            33.60        6.60             43.5600
36816            26            25.65       -0.35              0.1225
2503             71            65.58       -5.42             29.3764
53035             0             0.42        0.42              0.1764

### ___Improving the model____

In [ ]:
np.random.seed(42)
for i in range(10,110,10):
    print(f'trying with model with{i} estimators')
    model=RandomForestRegressor(n_estimators=i).fit(X_train,y_train)
    print(f'Model accuracy on test set:{model.score(X_test,y_test)*100}')
    print("")

trying with model with10 estimators
Model accuracy on test set:93.6531596317923

trying with model with20 estimators
Model accuracy on test set:94.03505029694111

trying with model with30 estimators
Model accuracy on test set:94.12331284319261

trying with model with40 estimators
Model accuracy on test set:94.21482399980185

trying with model with50 estimators
Model accuracy on test set:94.22049923273347

trying with model with60 estimators
Model accuracy on test set:94.22819732625321

trying with model with70 estimators
Model accuracy on test set:94.27087345243342

trying with model with80 estimators
Model accuracy on test set:94.27942218102213

trying with model with90 estimators
Model accuracy on test set:94.24680973853432

trying with model with100 estimators
Model accuracy on test set:94.2613663712304



### ___Saving the model___

In [ ]:
import pickle
pickle.dump(model,open("gym.pkl","wb"))

#### ___To load the model write the following code___

In [ ]:
# loaded_model=pickle.load(open("gym.pkl","rb"))
# loaded_model.score(X_test,y_test)

0.9424680973853432